#!/usr/bin/env node
/**
 * Export protocol wire fixtures as typed JSON samples for round-trip tests.
 *
 * Run after `cargo run -p protocol --bin export-fixtures`:
 *   pnpm codegen
 *
 * Plain JavaScript, not TypeScript: `node` runs this file directly, and it
 * cannot load a `.ts` one before v22.6 — the pinned toolchain and CI are on
 * v20. The one annotation this file ever had bought nothing a build script
 * needs, and a TS runner would be a dependency to keep a comment compiling.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const fixturesDir = path.join(here, "../tests/fixtures");
const outFile = path.join(here, "../src/runtime/generated/fixtures.ts");

function toExportName(file) {
  return file
    .replace(/\.json$/, "")
    .replace(/[^a-zA-Z0-9]+/g, "_")
    .replace(/^(\d)/, "_$1");
}

const files = fs
  .readdirSync(fixturesDir)
  .filter((name) => name.endsWith(".json"))
  .sort();

let body = `// AUTO-GENERATED by scripts/codegen-types.mjs — do not edit.
// Re-run: cargo run -p protocol --bin export-fixtures && pnpm codegen

`;

for (const file of files) {
  const raw = fs.readFileSync(path.join(fixturesDir, file), "utf8");
  const parsed = JSON.parse(raw);
  const name = toExportName(file);
  body += `export const ${name} = ${JSON.stringify(parsed, null, 2)} as const;\n\n`;
}

body += `export const FIXTURE_NAMES = ${JSON.stringify(files)} as const;\n`;

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, body);
console.log(`Wrote ${files.length} fixtures to ${path.relative(process.cwd(), outFile)}`);
