#!/usr/bin/env bun
import { mkdir } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { readJson } from "./files";

const fixturesDir = join(import.meta.dir, "../tests/fixtures");
const outFile = join(import.meta.dir, "../src/runtime/generated/fixtures.ts");
const MAX_FIXTURE_BYTES = 16 * 1024 * 1024;

function toExportName(file: string): string {
  return file
    .replace(/\.json$/, "")
    .replace(/[^a-zA-Z0-9]+/g, "_")
    .replace(/^(\d)/, "_$1");
}

const files = Array.from(new Bun.Glob("*.json").scanSync({ cwd: fixturesDir, dot: true })).sort();
let body = `// AUTO-GENERATED by scripts/codegen-types.ts — do not edit.
// Re-run: cargo run -p protocol --bin export-fixtures && bun run codegen

`;

for (const file of files) {
  const parsed = await readJson(join(fixturesDir, file), MAX_FIXTURE_BYTES);
  body += `export const ${toExportName(file)} = ${JSON.stringify(parsed, null, 2)} as const;\n\n`;
}

body += `export const FIXTURE_NAMES = ${JSON.stringify(files)} as const;\n`;
await mkdir(dirname(outFile), { recursive: true });
await Bun.write(outFile, body);
console.log(`Wrote ${files.length} fixtures to ${relative(process.cwd(), outFile)}`);
