// CSS provides the first-paint theme before the runtime applies derived values.
import { resolve } from "node:path";
import { palettes, staticTokens, toCssVariables, type ThemeBaseId } from "../src/theme/tokens";

const out = resolve(import.meta.dir, "../src/theme/tokens.css");

function block(selector: string, vars: Record<string, string>): string {
  const body = Object.entries(vars)
    .map(([name, value]) => `  ${name}: ${value};`)
    .join("\n");
  return `${selector} {\n${body}\n}\n`;
}

const order = Object.keys(palettes) as ThemeBaseId[];
const parts = [
  "/* Generated by scripts/generate-tokens.ts — do not edit by hand. */",
  block(':root, [data-theme="forge-dark"]', toCssVariables(palettes["forge-dark"])),
  ...order
    .filter((id) => id !== "forge-dark")
    .map((id) => block(`[data-theme="${id}"]`, toCssVariables(palettes[id]))),
  "/* Semantic layer and scale — theme-independent, so emitted once. */",
  block(":root", staticTokens()),
];

await Bun.write(out, `${parts.join("\n")}\n`);
console.log(`wrote ${out}`);
